  version: '3.8'

  services:
    db:
      image: mysql:5.7
      container_name: mysql_container
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: testdb
      networks:
        - mynetwork

    web:
      build: .
      container_name: flask_app
      ports:
        - "5000:5000"
      depends_on:
        - db
      environment:
        MYSQL_HOST: db
        MYSQL_USER: root
        MYSQL_PASSWORD: rootpassword
        MYSQL_DATABASE: testdb
      networks:
        - mynetwork

  networks:
    mynetwork:
